export default {
  LIMITED_NUMBER_ADVERTISEMENT: 5,
  MAX_PRICE: 100000,
  MIN_PRICE: 0,
  MinPriceLimit: {
    BUNGALOW: 0,
    FLAT: 1000,
    HOTEL: 3000,
    HOUSE: 5000,
    PALACE: 10000,
  },
  MIN_ROOMS: 1,
  MAX_ROOMS: 6,
  FOREVER_ALONE: 1,
  MAX_GUESTS: 6,
  MAX_AVATAR: 10,
  MESSAGE_TIME: 2000,
  NUMBER_MARKERS: 10,
  TITLE_MIN: 30,
  TITLE_MAX: 100,
  COORDINATE_MAP: {
    lat: 35.68952,
    lng: 139.69199,
  },
  HousingType: {
    BUNGALOW: 'bungalow',
    FLAT: 'flat',
    HOTEL: 'hotel',
    HOUSE: 'house',
    PALACE: 'palace',
  },
  TitleCount: {
    MIN: 30,
    MAX: 100,
  },
  GuestsCount: {
    ONE: '1',
    TWO: '2',
    THREE: '3',
    ZERO: '0',
  },
  RoomsCount: {
    ONE: '1',
    TWO: '2',
    THREE: '3',
    HUNDRED: '100',
  },
  COUNT_MAP_ZOOM: 12,
  DEBOUNCE_DELAY: 500,
  IMAGE_FILE_TYPES: ['gif', 'jpg', 'jpeg', 'png'],
  ERROR_MESSAGE: 'Форма не отправлена. Попробуйте еще раз.',
  ERROR_MAP_MESSAGE: 'Ошибка при загрузке. Позже попробуйте еще раз.',
  PRICE_TYPE: {
    ANY: 'any',
    LOW: 'low',
    MIDDLE: 'middle',
    HIGH: 'high',
  },
  PRICE_RANGE: {
    MIDDLE: 10000,
    HIGH: 50000,
  },
  DEFAULT_AVATAR: 'img/muffin-grey.svg',
  MAX_POINTS_RENDER_LIMIT: 10,
};
